name: 'CDEvents Action'
description: 'CDEvents'
author: 'CDEvents Team'
branding:
  icon: 'rss'
  color: 'green'
inputs:
  source:
    description: 'Source'
    required: true
  subject_id:
   description: Subject ID
   required: true
  subject_pipeline_name:
   description: Subject Pipeline Name
   required: true
  subject_url:
    description: Subject URL
    required: true
  version:
    version:
      description: 'CDEvents Action Version'
      required:
      default: 0.0.1
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run shell script
      shell: bash
      run: ./entrypoint.sh
      env:
        INPUT_SOURCE: ${{ inputs.source }}
        INPUT_SUBJECT_ID: ${{ inputs.subject_id }}
        INPUT_SUBJECT_PIPELINE_NAME: ${{ inputs.subject_pipeline_name }}
        INPUT_SUBJECT_URL: ${{ inputs.subject_url }}
        INPUT_VERSION: ${{ inputs.version }}

